name: Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Build binaries
        run: |
          # Linux
          GOOS=linux GOARCH=amd64 go build -o ztctl-linux-amd64 main.go
          GOOS=linux GOARCH=arm64 go build -o ztctl-linux-arm64 main.go
          
          # MacOS
          GOOS=darwin GOARCH=amd64 go build -o ztctl-darwin-amd64 main.go
          GOOS=darwin GOARCH=arm64 go build -o ztctl-darwin-arm64 main.go
          
          # Windows
          GOOS=windows GOARCH=amd64 go build -o ztctl-windows-amd64.exe main.go
          GOOS=windows GOARCH=arm64 go build -o ztctl-windows-arm64.exe main.go

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ztctl-linux-amd64
            ztctl-linux-arm64
            ztctl-darwin-amd64
            ztctl-darwin-arm64
            ztctl-windows-amd64.exe
            ztctl-windows-arm64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}